on:
  push:
    tags:
    - 'v*'

name: Build Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  build-linux-amd64:
    name: Build Linux/amd64
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Release Version
        id: get_version
        run: echo ::set-output name=release_version::${GITHUB_REF/refs\/tags\//}
      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: '~1.14.6'
      - name: Build Binary
        run: go build -o azure-cluster-upgrade
        env:
          GOARCH: amd64
          GOOS: linux
          CGO_ENABLED: "0"
      - name: Archive Artifact
        run: zip artifact.zip azure-cluster-upgrade
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./artifact.zip
          asset_name: azure-cluster-upgrade_${{ steps.get_version.outputs.release_version }}_linux_amd64.zip
          asset_content_type: application/zip
  build-darwin-amd64:
    name: Build Darwin/amd64
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: '~1.14.6'
      - name: Build Binary
        run: go build -o azure-cluster-upgrade
        env:
          GOARCH: amd64
          GOOS: darwin
      - name: Archive Artifact
        run: zip artifact.zip azure-cluster-upgrade
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./artifact.zip
          asset_name: azure-cluster-upgrade_${{ steps.get_version.outputs.release_version }}_darwin_amd64.zip
          asset_content_type: application/zip
  build-windows-amd64:
    name: Build Windows/amd64
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang Environment
        uses: actions/setup-go@v2
        with:
          go-version: '~1.14.6'
      - name: Build Binary
        run: go build -o azure-cluster-upgrade.exe
        env:
          GOARCH: amd64
          GOOS: windows
      - name: Archive Artifact
        run: zip artifact.zip azure-cluster-upgrade.exe
      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./artifact.zip
          asset_name: azure-cluster-upgrade_${{ steps.get_version.outputs.release_version }}_windows_amd64.zip
          asset_content_type: application/zip